server:
  port: 8080
spring:
  config:
    activate:
      on-profile:
  datasource:
    url: ${DB_CONNECTION_URL}
    driver-class-name: ${DB_CONNECTION_DRIVER}
    username: ${DB_CONNECTION_USERNAME}
    password: ${DB_CONNECTION_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create


---
jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-expire: ${JWT_TOKEN_EXPIRE}